# RuboCop’s default configuration: https://github.com/rubocop/rubocop/blob/master/config/default.yml
plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - test/*
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - test/*
    - test/**/*

Metrics/MethodLength:
  Max: 5
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Naming/PredicatePrefix:
  AllowedMethods:
    - has_many_path

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Lambda:
  EnforcedStyle: literal

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
