module Cards
  ACE_OF_SPADES = Card.parse("A♠")
  TWO_OF_SPADES = Card.parse("2♠")
  THREE_OF_SPADES = Card.parse("3♠")
  FOUR_OF_SPADES = Card.parse("4♠")
  FIVE_OF_SPADES = Card.parse("5♠")
  SIX_OF_SPADES = Card.parse("6♠")
  SEVEN_OF_SPADES = Card.parse("7♠")
  EIGHT_OF_SPADES = Card.parse("8♠")
  NINE_OF_SPADES = Card.parse("9♠")
  TEN_OF_SPADES = Card.parse("10♠")
  JACK_OF_SPADES = Card.parse("J♠")
  QUEEN_OF_SPADES = Card.parse("Q♠")
  KING_OF_SPADES = Card.parse("K♠")

  ACE_OF_HEARTS = Card.parse("A♥")
  TWO_OF_HEARTS = Card.parse("2♥")
  THREE_OF_HEARTS = Card.parse("3♥")
  FOUR_OF_HEARTS = Card.parse("4♥")
  FIVE_OF_HEARTS = Card.parse("5♥")
  SIX_OF_HEARTS = Card.parse("6♥")
  SEVEN_OF_HEARTS = Card.parse("7♥")
  EIGHT_OF_HEARTS = Card.parse("8♥")
  NINE_OF_HEARTS = Card.parse("9♥")
  TEN_OF_HEARTS = Card.parse("10♥")
  JACK_OF_HEARTS = Card.parse("J♥")
  QUEEN_OF_HEARTS = Card.parse("Q♥")
  KING_OF_HEARTS = Card.parse("K♥")

  ACE_OF_DIAMONDS = Card.parse("A♦")
  TWO_OF_DIAMONDS = Card.parse("2♦")
  THREE_OF_DIAMONDS = Card.parse("3♦")
  FOUR_OF_DIAMONDS = Card.parse("4♦")
  FIVE_OF_DIAMONDS = Card.parse("5♦")
  SIX_OF_DIAMONDS = Card.parse("6♦")
  SEVEN_OF_DIAMONDS = Card.parse("7♦")
  EIGHT_OF_DIAMONDS = Card.parse("8♦")
  NINE_OF_DIAMONDS = Card.parse("9♦")
  TEN_OF_DIAMONDS = Card.parse("10♦")
  JACK_OF_DIAMONDS = Card.parse("J♦")
  QUEEN_OF_DIAMONDS = Card.parse("Q♦")
  KING_OF_DIAMONDS = Card.parse("K♦")

  ACE_OF_CLUBS = Card.parse("A♣")
  TWO_OF_CLUBS = Card.parse("2♣")
  THREE_OF_CLUBS = Card.parse("3♣")
  FOUR_OF_CLUBS = Card.parse("4♣")
  FIVE_OF_CLUBS = Card.parse("5♣")
  SIX_OF_CLUBS = Card.parse("6♣")
  SEVEN_OF_CLUBS = Card.parse("7♣")
  EIGHT_OF_CLUBS = Card.parse("8♣")
  NINE_OF_CLUBS = Card.parse("9♣")
  TEN_OF_CLUBS = Card.parse("10♣")
  JACK_OF_CLUBS = Card.parse("J♣")
  QUEEN_OF_CLUBS = Card.parse("Q♣")
  KING_OF_CLUBS = Card.parse("K♣")
end
