name: "Ruby CI"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.115.3
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.115.3
        with:
          bundler-cache: true
      - name: Lint files
        run: bundle exec rake lint
